Data visualization for INTO-CPS-Association/DTaaS#99
INTO-CPS-Association/DTaaS-examples pull request #7
Opened 2023-10-30 13:49 UTC by yohan-unver

2023-10-30 14:44 UTC, prasadtalasila requested changes

2023-10-30 14:44 UTC, prasadtalasila commented on common/functions/issue99_2.ipynb
Please remove the result of running the jupyter notebook.
Also please check this in ml-workspace docker container

2023-10-30 14:44 UTC, prasadtalasila commented on common/functions/issue99_2.ipynb
Other observations: Please rename this file to cosim-output.ipynb

### Comments on first cell:

3. Add some more commands to show the list of available columns between lines 9 and 11. Have python commands to let user select one column. Please keep the existing code in lines 11 to 15.
4. Change title in line-16 to "Co-simulation outputs"
5. Change y-axis label on line-23 to "Multi-model connections"
6. Save files to "data/cosim/time-series.png or html"

### Comments on second cell:

1. Have a separate cell for showing start and end-time limits.
2. Separate cell for selecting start and end-times of categorization plot.
3. Have plot names as "data/cosim/categories.png or html"

Additions to plots:

1. New code at the end to let users select one-column of data for x-axis and another column for y-axis, and show a line-plot.

2023-10-30 14:44 UTC, prasadtalasila commented on common/data/data.csv
please rename and move this file to "cosim/maestro-output.csv"

2023-11-08 10:29 UTC, yohan-unver commented
I found the script that shows all the columns and let the user select one with a selector (allColumns.ipynb)

2023-11-12 20:40 UTC, prasadtalasila commented
merged in PR #8.

2023-11-12 20:40 UTC, closed without merging